baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Precious Energy'
theme = 'smol'

[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'images'
target = 'static/images'
